Flurry and Crushing Style resources
zunath/SWLOR_Haks pull request #159
Opened 2022-08-09 06:10 UTC by JohnWildkins

spaced out enough that they don't conflict with rock throw (other than having to tell git it's okay, I mean)

2022-08-12 00:26 UTC, zunath commented
Merge conflict on this one. Likely due to another PR being merged in.

2022-08-18 20:48 UTC, JohnWildkins commented
forgot to actually commit the baseitems.2da change that sets everything's base crit range to 20 (5%)

2022-09-09 01:02 UTC, zunath requested changes
Just need confirmation on the baseitems.2da file. Let me know, looks good otherwise.

2022-09-09 01:03 UTC, zunath commented on swlor2_2da/baseitems.2da
> +12    172        twobladedsword          2              5               0x1C010          1               2           WDbSw         0                1             1             1             it_bag
Well, just saw your comment above about the crit ranges. Sorry about that. This is fine to merge in. I will hold off on actually merging it until the changes in SWLOR_NWN are finished up.

2022-09-09 01:03 UTC, zunath approved these changes

2022-09-09 01:03 UTC, zunath commented
Holding on merging until changes in SWLOR_NWN are ready.

2022-09-12 14:56 UTC, merged