Ewok race haks
zunath/SWLOR_Haks pull request #238
Opened 2024-06-26 20:55 UTC by BamgaLab

implement graphical assets (4 head models for each gender, 8 portraits for each gender, custom hand and body models.)

2024-07-14 17:45 UTC, zunath commented on swlor2_parts/pfd0_bicepr208.mdl
> +# NeverBlender 4.0.5|Blender 4.0.2|2024-06-23
All mdl files need to be compiled.

2024-07-14 17:46 UTC, zunath commented on swlor2_2da/portraits.2da
> +4454   ewokM1_        0      169    ****            0      ****
There are a bunch of portraits listed here but I don't see the equivalent tga files in the swlor2_portraits folder.

2024-07-14 17:51 UTC, zunath requested changes
Please review requested changes above.

2024-07-17 19:39 UTC, taelon875 commented
Double Check your TLK, name of race and race description are not showing in game.

2024-07-17 23:06 UTC, taelon875 commented
Female Ewok head 111 has face and covering as the same "hair" option.  This differs from all other heads.

2024-07-20 02:33 UTC, merged